export const VOICE_OPTIONS = [
  { label: "Stephen – Sales and Customer Service",    provider: "11labs", voiceId: "3jR9BuQAOPMWUjWpi0ll" },
  { label: "Mark – Dynamic, Balanced and Emotional",  provider: "11labs", voiceId: "UgBBYS2sOqTuMpoF3BR0" },
  { label: "Jackson – American Tech Sales Rep",       provider: "11labs", voiceId: "2zGvynULFssveGrcP8hi" },
  { label: "George – Natural, Full and Confident",    provider: "11labs", voiceId: "YaarrMwvJxVUpjbZ2RpC" },
  { label: "Alex – Professional",                     provider: "11labs", voiceId: "pHqSZYhjNK8nDCPRglTL" },
  { label: "Matthew Logovik",                         provider: "11labs", voiceId: "1IthILLNX448pH19aMvC" },
  { label: "Voice A (7EzWGsX1…)",                     provider: "11labs", voiceId: "7EzWGsX10sAS4c9m9cPf" },
  { label: "Voice B (8fcyCHOz…)",                     provider: "11labs", voiceId: "8fcyCHOzlKDlxh1InJSf" },
  { label: "Voice C (sUzXYdok…)",                     provider: "11labs", voiceId: "sUzXYdokj3o9QQ91yPRF" },
  { label: "Voice D (E5vwBa1s…)",                     provider: "11labs", voiceId: "E5vwBa1swCEXshQFkLEu" },
  { label: "Voice E (4e32WqNV…)",                     provider: "11labs", voiceId: "4e32WqNVWRquDa1OcRYZ" },
  { label: "Voice F (mBqbvkxI…)",                     provider: "11labs", voiceId: "mBqbvkxIFe5HjjaoiN4P" },
  { label: "Voice G (e243k3Nw…)",                     provider: "11labs", voiceId: "e243k3NwaO5uqjBb8yKV" },
  { label: "Voice H (I1ejplf7…)",                     provider: "11labs", voiceId: "I1ejplf72DWHJzwAiw4n" },
] as const;
